trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
- stage: DevDeploy
- stage: QADeploy
- stage: PrdDeploy

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
