trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1erJob_BBBB 
    steps:
    - bash: echo Hola puto Build
    - bash: echo isino te kojo $(PipelineVariableLevel) veces
  - job: Job2doJob_BBBB
    steps:
    - bash: echo puto 2o Build  
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: Job1erJob_DEV
    steps:
    - bash: echo Hola puto DEV
    - bash: echo isino te kojo $(PipelineVariableLevel) veces
  - job: Job2doJob_DEV
    steps:
    - bash: echo puto 2o DEV  
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: Job1erJob_QA
    steps:
    - bash: echo Hola puto QA
    - bash: echo isino te kojo $(PipelineVariableLevel) veces
  - job: Job2doJob_QA
    steps:
    - bash: echo puto 2o QA  
- stage: PrdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: Job1erJob_PRD
    steps:
    - bash: echo Hola puto PRD
    - bash: echo isino te kojo $(PipelineVariableLevel) veces
  - job: Job2doJobPRD
    steps:
    - bash: echo puto 2o PRD  

